name: AI Security Gate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  security-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Gemini Security Audit
        env:
          GEMINI_API_KEY: "AQ.Ab8RN6LBpKs_NNmc5mX8-AUB0GGz6Nu7Wmh7T5i1d6tkIyk_0A"
        run: |
          python src/guard.py

